In [1]:
import numpy as np

In [3]:
np.__version__

'1.19.2'

In [4]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [5]:
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

In [6]:
a+b

[1, 2, 3, 4, 5, 6, 7, 8]

In [7]:
a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [8]:
a_array = np.array(a)
b_array = np.array(b)

print(a_array + b_array)
print(a_array * b_array)

[ 6  8 10 12]
[ 5 12 21 32]


In [9]:
m=np.array([[1,2,3],[4,5,6]])

In [10]:
type(m)


numpy.ndarray

In [11]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
m.shape

(2, 3)

In [14]:
m.size

6

In [19]:
zeros=np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [18]:
nol=np.zeros([5,2])
nol

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
soal1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
soal1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
soal2=np.array([[2,7,12,0],[3,9,3,4],[4,0,1,3]])
soal2

array([[ 2,  7, 12,  0],
       [ 3,  9,  3,  4],
       [ 4,  0,  1,  3]])

In [25]:
soal3=np.array([[1,2,3,4,5],[6,7,8,9,10]])
soal3.size

10

In [32]:
soal4=np.ones((2,3,3))
soal4

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [35]:
soal5=np.zeros((5,3))
soal5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
for i in range(2):
    soal5=soal5+np.ones((5,3))
soal5

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])