In [32]:
import numpy as np

## Exercise 4

### 1. create a null vector / 1D array of size 10 and update fifth value to 11.

In [3]:
x1 = np.zeros(10, dtype=int)
x1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
x1.size

10

In [4]:
x1[4]=11
x1

array([ 0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.,  0.])

### 2. Write a NumPy program to create a 2x3 arrays and change it into 3x2 arrays

In [7]:
x2=np.array([[1,2,3],[4,5,6]])
x2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
x2a=x2.reshape(3,2)
x2a

array([[1, 2],
       [3, 4],
       [5, 6]])

### 3. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

In [4]:
x3=np.ones((5,5))
x3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
x3[1:-1,1:-1]=0
x3

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### 4. Take a look at the following matrix. Access the [1, 1,2]

In [33]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])
z

array([[[ 0,  1,  3],
        [ 5,  7,  9],
        [ 6,  8, 10]],

       [[ 0,  2,  4],
        [ 6,  8, 10],
        [ 0,  1,  3]],

       [[ 1,  1,  2],
        [ 5,  2,  9],
        [ 1,  3,  3]]])

In [34]:
pos = np.where((z[:,:,0]==1) & (z[:,:,1]==1) & (z[:,:,2]==2))
pos

(array([2], dtype=int64), array([0], dtype=int64))

In [35]:
coord=list(zip(pos[0],pos[1]))
coord

[(2, 0)]

In [36]:
z[2,0]

array([1, 1, 2])

## ASSIGNMENT

### 1. Create a 4x4 matrix with values ranging from 0 to 3.

In [28]:
a10=np.arange(0,4).reshape((1,4))
a10

array([[0, 1, 2, 3]])

In [30]:
a11=np.vstack((a10,a10))
a12=np.vstack((a11,a11))
a12

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

### 2. Create and array with shape of 4x4 and turn it into two arrays along the second axis.

In [24]:
a2 = np.arange(1,17).reshape(4,4)
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [25]:
a2a=np.hsplit(a2,2)
a2a

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]